//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JpT.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JpT.Resource.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng tắt file Data trước khi kết thúc bài học để chương trình có thể cập nhật dữ liệu..
        /// </summary>
        internal static string MSG_CLOSE_FILE_DATA {
            get {
                return ResourceManager.GetString("MSG_CLOSE_FILE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã hoàn thành ôn tập Kanji của ngày hôm nay.
        ///Hãy quay lại đây vào ngày mai nhé!.
        /// </summary>
        internal static string MSG_KANJI_AGAIN_END {
            get {
                return ResourceManager.GetString("MSG_KANJI_AGAIN_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có từ Kanji nào cần ôn tập ngay trong ngày hôm nay.
        ///Hãy dành thời gian tiếp theo để củng cố ngữ pháp hoặc học thêm Từ vựng mới!.
        /// </summary>
        internal static string MSG_KANJI_AGAIN_NOT_NEED_LEARN {
            get {
                return ResourceManager.GetString("MSG_KANJI_AGAIN_NOT_NEED_LEARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vừa hoàn thành phần học Kanji mới của bài {0}..
        /// </summary>
        internal static string MSG_KANJI_NEW_END {
            get {
                return ResourceManager.GetString("MSG_KANJI_NEW_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có từ Kanji mới nào để học.
        ///Hãy bổ sung thêm từ Kanji vào file dữ liệu nhé!.
        /// </summary>
        internal static string MSG_KANJI_NEW_NOT_WORD {
            get {
                return ResourceManager.GetString("MSG_KANJI_NEW_NOT_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã hoàn thành ôn tập từ vựng của ngày hôm nay.
        ///Hãy quay lại đây vào ngày mai nhé!.
        /// </summary>
        internal static string MSG_KOTOBA_AGAIN_END {
            get {
                return ResourceManager.GetString("MSG_KOTOBA_AGAIN_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có từ vựng nào cần ôn tập ngay trong ngày hôm nay.
        ///Hãy dành thời gian tiếp theo để củng cố ngữ pháp hoặc học thêm Kanji mới!.
        /// </summary>
        internal static string MSG_KOTOBA_AGAIN_NOT_NEED_LEARN {
            get {
                return ResourceManager.GetString("MSG_KOTOBA_AGAIN_NOT_NEED_LEARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vừa hoàn thành phần học từ mới của bài {0}..
        /// </summary>
        internal static string MSG_KOTOBA_NEW_END {
            get {
                return ResourceManager.GetString("MSG_KOTOBA_NEW_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có từ mới nào để học.
        ///Hãy bổ sung thêm từ vựng vào file dữ liệu nhé!.
        /// </summary>
        internal static string MSG_KOTOBA_NEW_NOT_WORD {
            get {
                return ResourceManager.GetString("MSG_KOTOBA_NEW_NOT_WORD", resourceCulture);
            }
        }
    }
}
